<a href="https://colab.research.google.com/github/Sean1686/ai_foundation/blob/main/studentsPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

In [5]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("StudentsPerformance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())
print("First few rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

print("Missing values:")
print(df.isnull().sum())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First few rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  


In [10]:
print("Average score by columns:")
df[["math score", "reading score", "writing score"]].mean()

Average score by columns:


,0
math score,66.089
reading score,69.169
writing score,68.054


In [11]:
print("Maximum score by subject:")
df[["math score", "reading score", "writing score"]].max()

Maximum score by subject:


,0
math score,100
reading score,100
writing score,100


In [12]:
print("minimum score by subject:")
df[["math score", "reading score", "writing score"]].min()

minimum score by subject:


,0
math score,0
reading score,17
writing score,10


In [13]:
print("Corre  letion:")
df[["math score", "reading score", "writing score"]].corr()

Corre  letion:


,math score,reading score,writing score
math score,1.000000,0.817580,0.802642
reading score,0.817580,1.000000,0.954598
writing score,0.802642,0.954598,1.000000


In [17]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Pass", "Fail")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667   Pass
1          247      82.333333   Pass
2          278      92.666667   Pass
3          148      49.333333   Fail
4          229      76.333333   Pass


In [21]:
test_prep_group = df.groupby('test preparation course')[["math score", "reading score", "writing score"]].mean()
print("Average scores by test preparation course:")
print(test_prep_group)

# Gender-based average
gender_avg = df.groupby('gender')[["math score", "reading score", "writing score"]].mean()
print("\nAverage scores by gender:")
print(gender_avg)

# who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("\nPercentage of students who passed and failed:")
print(pass_rate)

Average scores by test preparation course:
                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

Average scores by gender:
        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

Percentage of students who passed and failed:
passed
Pass    89.7
Fail    10.3
Name: proportion, dtype: float64


In [22]:
# Convert Scores to Numpy Array
scores = df[["math score", "reading score", "writing score"]].values

# Mean, Std deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std Deviation:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-score (Normalized numbers)")
print(z_score[:5])
# Average 0 | Negative - | Positive +

Numpy Mean: [66.089 69.169 68.054]
Numpy Std Deviation: [15.15549666 14.59289002 15.18805728]
Z-score (Normalized numbers)
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]


In [23]:
# how many students scored above 90 average
top_scores = df[df["average score"] >= 90]
print("Top scored student above 90:", len(top_scores))

# how many failed?
failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored student above 90: 52
Failed from exam: 0
